# Generated by Django 3.1.4 on 2020-12-24 10:38

import Person.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeEmploey', models.DecimalField(decimal_places=0, max_digits=4)),
                ('nameArabic', models.CharField(max_length=30)),
                ('nameEnglish', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('nationalCode', models.DecimalField(decimal_places=0, max_digits=14)),
                ('mobileNum', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('religion', models.CharField(choices=[('مسلم', 'مسلم'), ('مسيحي', 'مسيحي')], max_length=10)),
                ('sex', models.CharField(choices=[('ذكر', 'ذكر'), ('انسة', 'انسة')], max_length=10)),
                ('socialStatus', models.CharField(choices=[('اعزب', 'اعزب'), ('متزوج', 'متزوج'), ('ارمل', 'ارمل'), ('مطلق', 'مطلق')], max_length=10)),
                ('birthDate', models.DateField(default='1111-11-11')),
                ('dateOfHiring', models.DateTimeField(auto_now=True)),
                ('dragaJops', models.CharField(max_length=100)),
                ('jop', models.CharField(max_length=100)),
                ('numInsurance', models.CharField(max_length=100)),
                ('healthInsurance', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=50)),
                ('fileStatus', models.CharField(choices=[('مكتمل', 'مكتمل'), ('غير مكتمل', 'غير مكتمل')], max_length=50)),
                ('صورة_شخصية', models.ImageField(upload_to=Person.models.image_upload)),
                ('صورة_شهادة_ميلاد', models.ImageField(upload_to=Person.models.image_upload)),
                ('صورة_التجنيد', models.ImageField(upload_to=Person.models.image_upload)),
                ('شهادة_التخرج', models.ImageField(upload_to=Person.models.image_upload)),
                ('صورة_مباشرة_عمل', models.ImageField(upload_to=Person.models.image_upload)),
                ('صورة_فيش_جنائي', models.ImageField(upload_to=Person.models.image_upload)),
                ('صورة_اقرار_استلام_عمل', models.ImageField(upload_to=Person.models.image_upload)),
                ('صورة_البطاقة', models.ImageField(upload_to=Person.models.image_upload)),
                ('صورة_كعب_عمل', models.ImageField(upload_to=Person.models.image_upload)),
                ('صورة_نموذج_111', models.ImageField(upload_to=Person.models.image_upload)),
            ],
        ),
    ]
