# Generated by Django 3.1.4 on 2020-12-24 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management', models.CharField(max_length=50)),
                ('manage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manage', to='Person.personal')),
            ],
        ),
    ]
