# Generated by Django 3.1.4 on 2020-12-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0002_management'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Management',
        ),
    ]
