# Generated by Django 3.1.4 on 2020-12-24 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0004_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='management',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Person.management'),
            preserve_default=False,
        ),
    ]
