# Generated by Django 3.1.4 on 2020-12-27 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0005_personal_management'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='codeEmploey',
        ),
    ]
