# Generated by Django 3.1.4 on 2020-12-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0006_remove_personal_codeemploey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='dateOfHiring',
        ),
    ]
