# Generated by Django 3.1.4 on 2020-12-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0007_remove_personal_dateofhiring'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='dateOfHiring',
            field=models.DateField(default='2021-01-01'),
        ),
    ]
