# Generated by Django 3.1.4 on 2020-12-28 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0008_personal_dateofhiring'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='vacations',
            field=models.IntegerField(default=25),
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFr', models.DateField()),
                ('dateLs', models.DateField()),
                ('vacation', models.CharField(choices=[('A', 'عارضة'), ('B', 'مرضي'), ('C', 'اعتيادي'), ('D', 'بدون مرتب')], max_length=15)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vacation', to='Person.personal')),
            ],
        ),
    ]
