# Generated by Django 3.1.4 on 2020-12-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0009_auto_20201228_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='vacations',
            field=models.IntegerField(default=21),
        ),
    ]
