# Generated by Django 3.1.4 on 2020-12-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0010_auto_20201228_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='vacation_num',
            field=models.IntegerField(default=0),
        ),
    ]
