# Generated by Django 3.1.4 on 2020-12-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0011_vacation_vacation_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='vacations',
            field=models.IntegerField(default=0),
        ),
    ]
