# Generated by Django 3.1.4 on 2021-01-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0012_auto_20201229_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='codeEmploey',
            field=models.DecimalField(decimal_places=0, default=1100, max_digits=4),
            preserve_default=False,
        ),
    ]
